spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/alvear_club?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# OBLIGAMOS a usar el dialecto de MySQL (La "vieja confiable")
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true